#!/usr/bin/env ruby -w
             
# Muppet: The Static bot 
# Using an array-based bot with static responses
# was originally conceived by my co-worker Daniel Wikstrom.
# This particular strategy was generated by randomly
# creating strategies and then letting the strategies to 
# fight each other.  
strategy = [4, 2, 5, 6, 1, 7, 11, 8, 12, 3, 13, 9, 10]

13.times do
  $stdout.puts strategy[$stdin.gets[/\d+/].to_i - 1]
  $stdout.flush
  $stdin.gets
end

