$expectations = {
  %w[pro 1 sal] => 'provencal',
  %w[2 thing] => 'toothing',
  %w[r b trash] => 'arbitrage',
  %w[mon 3 l] => 'montreal',
  %w[3 men dose] => 'tremendous',
  %w[mid wind r] => 'midwinter',
  %w[yes tier knight] => 'yesternight',
  %w[mar well s]=>'marvelous',
  %w[vert x]=>'vertex',
  %w[ban l eyes] => 'banalize',
  %w[harm n eyes] => 'harmonize',
  %w[harm o niece east] => 'harmonicist',
  %w[knight in gale] => 'nightingale',
  %w[knee hill east] => 'nihilist',
  %w[mass car pone a] => 'mascarpone',
  %w[cock knee] => 'cockney',
}
