require "rake/rdoctask"
require "rake/testtask"

task :default => [:test]

Rake::TestTask.new do |test|
	test.libs << "test"
	test.test_files = [ "test/ts_all.rb" ]
	test.verbose = true
end

Rake::RDocTask.new do |rdoc|
	rdoc.main = "README"
	rdoc.rdoc_files.include("README", "lib/")
	rdoc.rdoc_dir = "doc/html"
	rdoc.title = "Chess Library Documentation"
end

desc "Play Ruby Quiz Chess"
task :play do
	ruby "-Ibin:lib bin/chess"
end
