#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "brackets.y".
#

require 'racc/parser'


class BracketParser < Racc::Parser

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 10, :_reduce_none,
 3, 12, :_reduce_none,
 3, 14, :_reduce_none,
 3, 15, :_reduce_none,
 1, 11, :_reduce_none,
 1, 11, :_reduce_none,
 1, 11, :_reduce_none,
 1, 16, :_reduce_none,
 2, 16, :_reduce_none,
 1, 17, :_reduce_none,
 2, 17, :_reduce_none,
 1, 13, :_reduce_none,
 1, 13, :_reduce_none ]

racc_reduce_n = 14

racc_shift_n = 23

racc_action_table = [
     3,     3,     6,     6,     7,     7,    13,    13,     3,     3,
     6,     6,     7,     7,    13,     3,    16,     6,    18,     7,
    13,    20,    21,    22 ]

racc_action_check = [
     7,     3,     7,     3,     7,     3,     7,     3,     6,     0,
     6,     0,     6,     0,     6,     9,     8,     9,    10,     9,
    13,    14,    15,    16 ]

racc_action_pointer = [
     7,   nil,   nil,    -1,   nil,   nil,     6,    -2,    16,    13,
    15,   nil,   nil,    12,    16,    15,    23,   nil,   nil,   nil,
   nil,   nil,   nil ]

racc_action_default = [
   -14,    -1,    -5,   -14,    -6,    -7,   -14,   -14,   -14,   -10,
   -14,   -12,   -13,    -8,   -14,   -14,   -14,   -11,    -2,    -9,
    -3,    -4,    23 ]

racc_goto_table = [
    10,     8,     1,    14,    15,    19,    17 ]

racc_goto_check = [
     4,     1,     2,     4,     4,     7,     8 ]

racc_goto_pointer = [
   nil,     1,     2,   nil,    -3,   nil,   nil,    -8,    -3 ]

racc_goto_default = [
   nil,   nil,     9,     2,   nil,     4,     5,    11,    12 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 "{" => 2,
 "}" => 3,
 "[" => 4,
 "]" => 5,
 "(" => 6,
 ")" => 7,
 "B" => 8 }

racc_use_result_var = true

racc_nt_base = 9

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'"{"',
'"}"',
'"["',
'"]"',
'"("',
'")"',
'"B"',
'$start',
'pack_string',
'packing',
'curly',
'pack_expr',
'square',
'round',
'bs',
'packing_list']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

 # reduce 2 omitted

 # reduce 3 omitted

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

 # reduce 11 omitted

 # reduce 12 omitted

 # reduce 13 omitted

 def _reduce_none( val, _values, result )
  result
 end

end   # class BracketParser
