require "rake/rdoctask"
require "rake/testtask"

task :default => [:test]

Rake::TestTask.new do |test|
	test.libs << "test"
	test.test_files = [ "test/ts_all.rb" ]
	test.verbose = true
end

Rake::RDocTask.new do |rdoc|
	rdoc.main = "README"
	rdoc.rdoc_files.include("README", "lib/")
	rdoc.rdoc_dir = "doc/html"
	rdoc.title = "Chess Library Documentation"
end

desc "Play Ruby Quiz Chess"
task :play do
	ruby "-Ibin:lib bin/chess"
end
desc "Play Ruby Quiz Fibonacci Chess"
task :play_fib do
	ruby "-Ibin:lib bin/fibonacci_chess"
end
desc "Play Ruby Quiz Gun Chess"
task :play_gun do
	ruby "-Ibin:lib bin/gun_chess"
end
desc "Play Ruby Quiz Blackhole Chess"
task :play_hole do
	ruby "-Ibin:lib bin/blackhole_chess"
end
desc "Play Ruby Quiz Fairy Chess"
task :play_fairy do
	ruby "-Ibin:lib bin/fairy_chess"
end
